theme: jekyll-theme-hacker
title: GREPSEC V
description: GREPSEC is a workshop for early-stage graduate students in computer security and privacy, specifically women and members of underrepresented groups in this field. 
