theme: jekyll-theme-hacker
title: GREPSEC V (Virtual)
description: August 5-6, 2021
show_downloads: false
logo: assets/images/gsec-symbol-lo2.gif
favicon: assets/images/grepsec.ico

#  path: assets/images/grepsecIV.jpg
#  height: 150
